In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Carga de csvs para exploración

df_universo  = pd.read_csv('data/universo.csv')
df_base_clientes  = pd.read_csv('data/base_clientes.csv')
df_base_saldos_cuentas  = pd.read_csv('data/base_saldos_cuentas.csv')

**Explorando df_universo**

In [2]:
duplicados = df_universo.duplicated(subset='ID', keep=False).sum()
print(f"Número de registros con 'ID' duplicado: {duplicados}")

Número de registros con 'ID' duplicado: 0

In [3]:
df_universo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535943 entries, 0 to 535942
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   ID       535943 non-null  object
 1   target   535943 non-null  int64
 2   periodo  535943 non-null  object
dtypes: int64(1), object(2)
memory usage: 12.3+ MB

In [4]:
df_universo.target.value_counts()

target
0    464075
1     47171
5      8489
4      6893
2      5929
3      3386
Name: count, dtype: int64

**EXPLORANDO BASE_CLIENTES**

In [5]:

df_base_clientes.head()

,ID,edad,ingreso,anios_exp,tipo_empleo,buro_de_credito,pago_nomina,tc,prest_per,prest_veh_hip,cuenta_ahorro,ofer_prest_per,ofer_tc,ofer_compra_deuda
0,42af3bf64c2c14307361e970e76c9653df78b215838971...,4.2484,4.1259,0.0,type_2,category_4,4.8095,Yes,No,No,Yes,No,No,No
1,5ab9acd6dc30e0e9361ca53e797b40f68841bd698d0926...,4.6903,3.9570,0.0,type_7,category_9,0.0000,No,No,No,Yes,No,No,No
2,8e40f988dd93417a0a40c32e65386425d891c879fedf4c...,4.1682,4.4640,0.0,type_7,category_5,0.0000,No,No,No,Yes,No,No,No
3,0e48974ce6e81d9e81a8da780521a2f98fb2385dc879df...,3.9651,4.0966,0.0,type_7,category_3,0.0000,Yes,Yes,Yes,Yes,No,No,No
4,e033c53b4fb230de5da6868503a9e079b289e064d62de4...,3.9576,4.1876,0.0,type_7,category_5,0.0000,Yes,No,No,Yes,No,No,No

In [6]:
df_base_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 809579 entries, 0 to 809578
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 809579 non-null  object
 1   edad               809579 non-null  float64
 2   ingreso            809579 non-null  float64
 3   anios_exp          809579 non-null  float64
 4   tipo_empleo        809579 non-null  object
 5   buro_de_credito    809579 non-null  object
 6   pago_nomina        809579 non-null  float64
 7   tc                 809579 non-null  object
 8   prest_per          809579 non-null  object
 9   prest_veh_hip      809579 non-null  object
 10  cuenta_ahorro      809579 non-null  object
 11  ofer_prest_per     809579 non-null  object
 12  ofer_tc            809579 non-null  object
 13  ofer_compra_deuda  809579 non-null  object
dtypes: float64(4), object(10)
memory usage: 86.5+ MB

In [7]:
df_base_clientes.describe()

                edad        ingreso      anios_exp    pago_nomina
count  809579.000000  809579.000000  809579.000000  809579.000000
mean        4.275201       4.284237       1.333632       1.417533
std         0.377544       0.477204       1.946502       2.017392
min         0.000000       0.000000       0.000000       0.000000
25%         4.001100       4.098200       0.000000       0.000000
50%         4.266700       4.286900       0.000000       0.000000
75%         4.549500       4.509800       3.619300       3.973700
max         5.000000       5.000000       5.000000       5.000000

In [8]:
df_base_clientes.duplicated().sum()

np.int64(0)

**Creación de variables para df_base_clientes**

**Creación de nuevas variables derivadas [der_var1_var2]**

In [9]:
df_base_clientes['der_ingreso_por_anio_exp'] = df_base_clientes['ingreso'] / (df_base_clientes['anios_exp'] + 1)
df_base_clientes['der_edad_laboral_relativa'] = df_base_clientes['anios_exp'] / (df_base_clientes['edad'] + 1)
df_base_clientes['der_edad_ingreso_relativa'] = df_base_clientes['ingreso'] / (df_base_clientes['edad'] + 1)
df_base_clientes['der_edad_anios_exp'] = df_base_clientes['edad'] / (df_base_clientes['anios_exp'] + 1)
df_base_clientes['der_ingreso_edad_exp'] = df_base_clientes['ingreso'] / ((df_base_clientes['edad'] + 1) * (df_base_clientes['anios_exp'] + 1))
df_base_clientes['der_ingreso_vs_nomina'] = df_base_clientes['pago_nomina'] / (df_base_clientes['ingreso'] + 1)
df_base_clientes['der_nomina_vs_exp'] = df_base_clientes['pago_nomina'] / (df_base_clientes['anios_exp'] + 1)
df_base_clientes['der_ingreso_nomina_ratio'] = (df_base_clientes['ingreso'] - df_base_clientes['pago_nomina']) / (df_base_clientes['ingreso'] + 1)

In [10]:
df_base_clientes['num_productos'] = (
    (df_base_clientes['tc'] == 'Yes').astype(int) +
    (df_base_clientes['prest_per'] == 'Yes').astype(int) +
    (df_base_clientes['prest_veh_hip'] == 'Yes').astype(int) +
    (df_base_clientes['cuenta_ahorro'] == 'Yes').astype(int)
)

df_base_clientes['num_ofertas'] = (
    (df_base_clientes['ofer_prest_per'] == 'Yes').astype(int) +
    (df_base_clientes['ofer_tc'] == 'Yes').astype(int) +
    (df_base_clientes['ofer_compra_deuda'] == 'Yes').astype(int)
)

df_base_clientes['relacion_ofertas_uso'] = df_base_clientes['num_productos'] / (df_base_clientes['num_ofertas'] + 1)

In [11]:
df_base_clientes['usa_tc_y_ahorro'] = ((df_base_clientes['tc'] == 'Yes') & (df_base_clientes['cuenta_ahorro'] == 'Yes')).astype(int)
df_base_clientes['usa_prestamo_y_tc'] = ((df_base_clientes['prest_per'] == 'Yes') & (df_base_clientes['tc'] == 'Yes')).astype(int)
df_base_clientes['tiene_creditos_multiples'] = ((df_base_clientes['prest_per'] == 'Yes') & (df_base_clientes['prest_veh_hip'] == 'Yes')).astype(int)

In [12]:
df_base_clientes['oferta_credito_activo'] = ((df_base_clientes['ofer_prest_per'] == 'Yes') | (df_base_clientes['ofer_tc'] == 'Yes')).astype(int)
df_base_clientes['oferta_total_vs_uso'] = df_base_clientes['num_ofertas'] / (df_base_clientes['num_productos'] + 1)

In [13]:
df_base_clientes['riesgo_credito_grupo'] = df_base_clientes['buro_de_credito'].map({'category_1': 1, 'category_2': 2, 'category_3': 3, 'category_4': 4, 'category_5': 5, 'category_6': 6, 'category_7': 7, 'category_8': 8, 'category_9': 9})

Concatenar tablas

In [14]:
import pandas as pd

# Asegúrate de tener una columna común para hacer el join, por ejemplo 'ID'
# (ajusta 'ID' si el nombre de la llave es diferente)

# 1️⃣ Renombrar las columnas de df_base_clientes (excepto la llave)
df_base_clientes_prefixed = df_base_clientes.rename(
    columns={col: f"DB_CLI_{col}" for col in df_base_clientes.columns if col != 'ID'}
)

# 2️⃣ Realizar el LEFT JOIN con df_universo
df_universo = df_universo.merge(
    df_base_clientes_prefixed,
    on='ID',
    how='left'
)

# 3️⃣ Verificación
print(df_universo.shape)
df_universo.head()

(535943, 33)

,ID,target,periodo,DB_CLI_edad,DB_CLI_ingreso,DB_CLI_anios_exp,DB_CLI_tipo_empleo,DB_CLI_buro_de_credito,DB_CLI_pago_nomina,DB_CLI_tc,...,DB_CLI_der_ingreso_nomina_ratio,DB_CLI_num_productos,DB_CLI_num_ofertas,DB_CLI_relacion_ofertas_uso,DB_CLI_usa_tc_y_ahorro,DB_CLI_usa_prestamo_y_tc,DB_CLI_tiene_creditos_multiples,DB_CLI_oferta_credito_activo,DB_CLI_oferta_total_vs_uso,DB_CLI_riesgo_credito_grupo
0,4d5a33701cb5b30b0b0a924d80de4ae78fbd0b54e2117f...,0,period_5,3.8498,4.6527,0.000,type_2,category_6,0.0,No,...,0.823093,1,0,1.000000,0,0,0,0,0.0,6
1,bf7092e5f394d266143dfe90b3fc73eac51f0b0084d7a3...,0,period_5,4.5476,4.2447,4.274,type_3,category_4,0.0,No,...,0.809331,1,0,1.000000,0,0,0,0,0.0,4
2,270d8f8f607d19886c50edb7746c3670194134b56d31e2...,0,period_5,4.3600,4.2117,0.000,type_2,category_9,0.0,No,...,0.808124,1,0,1.000000,0,0,0,0,0.0,9
3,5e6b7bea5e4911329669f45728d3398ad54dfe11fbb16d...,0,period_5,4.3914,4.1584,0.000,type_7,category_2,0.0,No,...,0.806141,1,2,0.333333,0,0,0,1,1.0,2
4,98954adf775b9fce1c9e311a025ec3e0a1c6e90f991ef7...,0,period_5,4.3077,4.3285,0.000,type_2,category_6,0.0,No,...,0.812330,1,0,1.000000,0,0,0,0,0.0,6

In [15]:
df_universo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535943 entries, 0 to 535942
Data columns (total 33 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   ID                                535943 non-null  object
 1   target                            535943 non-null  int64
 2   periodo                           535943 non-null  object
 3   DB_CLI_edad                       535943 non-null  float64
 4   DB_CLI_ingreso                    535943 non-null  float64
 5   DB_CLI_anios_exp                  535943 non-null  float64
 6   DB_CLI_tipo_empleo                535943 non-null  object
 7   DB_CLI_buro_de_credito            535943 non-null  object
 8   DB_CLI_pago_nomina                535943 non-null  float64
 9   DB_CLI_tc                         535943 non-null  object
 10  DB_CLI_prest_per                  535943 non-null  object
 11  DB_CLI_prest_veh_hip              535943 non-null  object
 12  DB_CLI_cuenta_ahorro              535943 non-null  object
 13  DB_CLI_ofer_prest_per             535943 non-null  object
 14  DB_CLI_ofer_tc                    535943 non-null  object
 15  DB_CLI_ofer_compra_deuda          535943 non-null  object
 16  DB_CLI_der_ingreso_por_anio_exp   535943 non-null  float64
 17  DB_CLI_der_edad_laboral_relativa  535943 non-null  float64
 18  DB_CLI_der_edad_ingreso_relativa  535943 non-null  float64
 19  DB_CLI_der_edad_anios_exp         535943 non-null  float64
 20  DB_CLI_der_ingreso_edad_exp       535943 non-null  float64
 21  DB_CLI_der_ingreso_vs_nomina      535943 non-null  float64
 22  DB_CLI_der_nomina_vs_exp          535943 non-null  float64
 23  DB_CLI_der_ingreso_nomina_ratio   535943 non-null  float64
 24  DB_CLI_num_productos              535943 non-null  int64
 25  DB_CLI_num_ofertas                535943 non-null  int64
 26  DB_CLI_relacion_ofertas_uso       535943 non-null  float64
 27  DB_CLI_usa_tc_y_ahorro            535943 non-null  int64
 28  DB_CLI_usa_prestamo_y_tc          535943 non-null  int64
 29  DB_CLI_tiene_creditos_multiples   535943 non-null  int64
 30  DB_CLI_oferta_credito_activo      535943 non-null  int64
 31  DB_CLI_oferta_total_vs_uso        535943 non-null  float64
 32  DB_CLI_riesgo_credito_grupo       535943 non-null  int64
dtypes: float64(14), int64(8), object(11)
memory usage: 134.9+ MB

In [16]:
duplicados = df_universo.duplicated(subset='ID', keep=False).sum()
print(f"Número de registros con 'ID' duplicado: {duplicados}")

Número de registros con 'ID' duplicado: 0

**Explorando df_base_saldos_cuentas**

In [17]:
df_base_saldos_cuentas.head()

,mes,ID,saldo_ahorros,saldo_otros,periodo
0,11,c7a6cecac361a970ee6c7cb9f2679c38c668940c6ebdc5...,4.1900,0.0,period_5
1,12,68f89dc7efe7cd1ce3cf6d52d8867bd2b84f236736bf91...,4.4621,0.0,period_5
2,2,e3f6afb18792d0b97cb9a63ad9567bbd106146c78d212a...,4.2878,0.0,period_5
3,1,8993170400939d522bdc72707527f5ab90202119fe3cab...,5.0000,5.0,period_5
4,7,399d686897232a55c713d61a6bdc7e232ab85b864d6288...,3.8922,0.0,period_5

In [18]:
df_base_saldos_cuentas.head()

,mes,ID,saldo_ahorros,saldo_otros,periodo
0,11,c7a6cecac361a970ee6c7cb9f2679c38c668940c6ebdc5...,4.1900,0.0,period_5
1,12,68f89dc7efe7cd1ce3cf6d52d8867bd2b84f236736bf91...,4.4621,0.0,period_5
2,2,e3f6afb18792d0b97cb9a63ad9567bbd106146c78d212a...,4.2878,0.0,period_5
3,1,8993170400939d522bdc72707527f5ab90202119fe3cab...,5.0000,5.0,period_5
4,7,399d686897232a55c713d61a6bdc7e232ab85b864d6288...,3.8922,0.0,period_5

In [19]:
df_base_saldos_cuentas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8876560 entries, 0 to 8876559
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   mes            int64
 1   ID             object
 2   saldo_ahorros  float64
 3   saldo_otros    float64
 4   periodo        object
dtypes: float64(2), int64(1), object(2)
memory usage: 338.6+ MB

In [20]:
df_base_saldos_cuentas.describe()

                mes  saldo_ahorros   saldo_otros
count  8.876560e+06   8.876560e+06  8.876560e+06
mean   6.632422e+00   3.140673e+00  6.191672e-01
std    3.448429e+00   1.207045e+00  1.405347e+00
min    1.000000e+00   0.000000e+00  0.000000e+00
25%    4.000000e+00   2.644100e+00  0.000000e+00
50%    7.000000e+00   3.318500e+00  0.000000e+00
75%    1.000000e+01   3.986700e+00  0.000000e+00
max    1.200000e+01   5.000000e+00  5.000000e+00

**Creación de variables para df_base_saldos_cuentas**

In [21]:
import pandas as pd
from functools import reduce

# -------------------------------------------------------------
# ORDEN Y CONFIGURACIÓN BASE
# -------------------------------------------------------------
df_base_saldos_cuentas = df_base_saldos_cuentas.sort_values(by=['ID', 'mes'], ascending=[True, False])

# Detectar el mes máximo disponible (por si no es diciembre)
mes_max = df_base_saldos_cuentas['mes'].max()

# -------------------------------------------------------------
# FUNCIÓN PARA AGREGAR LOS ÚLTIMOS n MESES
# -------------------------------------------------------------
def agregar_por_meses(df, n, mes_max):
    """
    Calcula agregados de saldo de ahorros (max, min, sum, mean)
    para los últimos n meses de cada cliente.
    """
    meses = list(range(mes_max, mes_max - n, -1))  # Ejemplo: si mes_max=12, n=3 → [12,11,10]
    sufijo = f"{n}_meses"
    
    return (
        df[df['mes'].isin(meses)]
        .groupby('ID', as_index=False)
        .agg(
            **{
                f"{sufijo}_max_saldo_ahorros": ('saldo_ahorros', 'max'),
                f"{sufijo}_min_saldo_ahorros": ('saldo_ahorros', 'min'),
                f"{sufijo}_sum_saldo_ahorros": ('saldo_ahorros', 'sum'),
                f"{sufijo}_prom_saldo_ahorros": ('saldo_ahorros', 'mean'),
            }
        )
    )

# -------------------------------------------------------------
# GENERACIÓN AUTOMÁTICA DE AGREGADOS (2 A 12 MESES)
# -------------------------------------------------------------
agregados_list = [
    agregar_por_meses(df_base_saldos_cuentas, n, mes_max)
    for n in range(2, 13)
]

# -------------------------------------------------------------
# UNIÓN FINAL DE TODOS LOS AGREGADOS POR ID
# -------------------------------------------------------------
df_agregados_base_saldos_cuentas = reduce(
    lambda left, right: pd.merge(left, right, on='ID', how='left'),
    agregados_list
)

# -------------------------------------------------------------
# REVISIÓN FINAL
# -------------------------------------------------------------
print(f"Shape final: {df_agregados_base_saldos_cuentas.shape}")
df_agregados_base_saldos_cuentas.head()

Shape final: (784556, 45)

,ID,2_meses_max_saldo_ahorros,2_meses_min_saldo_ahorros,2_meses_sum_saldo_ahorros,2_meses_prom_saldo_ahorros,3_meses_max_saldo_ahorros,3_meses_min_saldo_ahorros,3_meses_sum_saldo_ahorros,3_meses_prom_saldo_ahorros,4_meses_max_saldo_ahorros,...,10_meses_sum_saldo_ahorros,10_meses_prom_saldo_ahorros,11_meses_max_saldo_ahorros,11_meses_min_saldo_ahorros,11_meses_sum_saldo_ahorros,11_meses_prom_saldo_ahorros,12_meses_max_saldo_ahorros,12_meses_min_saldo_ahorros,12_meses_sum_saldo_ahorros,12_meses_prom_saldo_ahorros
0,00000f6dd2df6f081ce59cc4490f152e3fd5695de62bd9...,2.0478,1.9315,3.9793,1.98965,3.2484,1.9315,7.2277,2.409233,3.4815,...,15.7029,1.57029,3.4815,0.4939,16.2953,1.481391,3.4815,0.4939,16.8877,1.407308
1,000043cc1abd7597c99f494cc523ff99a4e0e64e98b128...,3.5701,2.7086,6.2787,3.13935,3.5701,2.7086,9.1865,3.062167,3.5701,...,33.4863,3.34863,3.9980,2.6010,36.0873,3.280664,3.9980,2.3428,38.4301,3.202508
2,000095b7b77ff622b2130f2d4bfa1e8d81f1fc4580a248...,3.9865,3.9865,7.9730,3.98650,3.9865,3.9865,11.9595,3.986500,3.9865,...,39.8650,3.98650,3.9865,3.9865,43.8515,3.986500,3.9865,3.9865,47.8380,3.986500
3,00009bb00e84af44d1abc86b9fbd155842ffef6cad814d...,4.0610,4.0464,8.1074,4.05370,4.0791,4.0464,12.1865,4.062167,4.0946,...,42.1374,4.21374,4.3968,4.0464,46.4952,4.226836,4.3968,4.0464,50.7124,4.226033
4,0000a9728fc57abef25c2fc0424c9c907a5559e7b8b559...,3.9150,2.8720,6.7870,3.39350,3.9150,2.8720,9.6760,3.225333,3.9150,...,27.7544,2.77544,3.9150,2.0286,30.7387,2.794427,3.9150,2.0286,33.7255,2.810458

In [22]:
# -------------------------------------------------------------
# CREAR NUEVOS AGREGADOS ROLLING
# -------------------------------------------------------------
df_agregados_roll = df_base_saldos_cuentas.groupby('ID', as_index=False).agg(
    std_3m_ahorros=('saldo_ahorros', lambda x: x.rolling(3, min_periods=1).std().iloc[-1]),
    cv_3m_ahorros=('saldo_ahorros', lambda x: (x.rolling(3, min_periods=1).std() / (x.rolling(3, min_periods=1).mean() + 1e-6)).iloc[-1])
)

# -------------------------------------------------------------
# UNIÓN CON LOS AGREGADOS ANTERIORES
# -------------------------------------------------------------
df_agregados_base_saldos_cuentas = pd.merge(
    df_agregados_base_saldos_cuentas,
    df_agregados_roll,
    on='ID',
    how='left'
)

# -------------------------------------------------------------
# REVISIÓN FINAL
# -------------------------------------------------------------
print(f"Shape final: {df_agregados_base_saldos_cuentas.shape}")
df_agregados_base_saldos_cuentas.head()

Shape final: (784556, 47)

,ID,2_meses_max_saldo_ahorros,2_meses_min_saldo_ahorros,2_meses_sum_saldo_ahorros,2_meses_prom_saldo_ahorros,3_meses_max_saldo_ahorros,3_meses_min_saldo_ahorros,3_meses_sum_saldo_ahorros,3_meses_prom_saldo_ahorros,4_meses_max_saldo_ahorros,...,11_meses_max_saldo_ahorros,11_meses_min_saldo_ahorros,11_meses_sum_saldo_ahorros,11_meses_prom_saldo_ahorros,12_meses_max_saldo_ahorros,12_meses_min_saldo_ahorros,12_meses_sum_saldo_ahorros,12_meses_prom_saldo_ahorros,std_3m_ahorros,cv_3m_ahorros
0,00000f6dd2df6f081ce59cc4490f152e3fd5695de62bd9...,2.0478,1.9315,3.9793,1.98965,3.2484,1.9315,7.2277,2.409233,3.4815,...,3.4815,0.4939,16.2953,1.481391,3.4815,0.4939,16.8877,1.407308,0.535319,0.593831
1,000043cc1abd7597c99f494cc523ff99a4e0e64e98b128...,3.5701,2.7086,6.2787,3.13935,3.5701,2.7086,9.1865,3.062167,3.5701,...,3.9980,2.6010,36.0873,3.280664,3.9980,2.3428,38.4301,3.202508,0.700319,0.244073
2,000095b7b77ff622b2130f2d4bfa1e8d81f1fc4580a248...,3.9865,3.9865,7.9730,3.98650,3.9865,3.9865,11.9595,3.986500,3.9865,...,3.9865,3.9865,43.8515,3.986500,3.9865,3.9865,47.8380,3.986500,0.000000,0.000000
3,00009bb00e84af44d1abc86b9fbd155842ffef6cad814d...,4.0610,4.0464,8.1074,4.05370,4.0791,4.0464,12.1865,4.062167,4.0946,...,4.3968,4.0464,46.4952,4.226836,4.3968,4.0464,50.7124,4.226033,0.094468,0.021848
4,0000a9728fc57abef25c2fc0424c9c907a5559e7b8b559...,3.9150,2.8720,6.7870,3.39350,3.9150,2.8720,9.6760,3.225333,3.9150,...,3.9150,2.0286,30.7387,2.794427,3.9150,2.0286,33.7255,2.810458,0.021427,0.007207

In [23]:
df_base_saldos_cuentas['ratio_ahorros_otros'] = (
    df_base_saldos_cuentas['saldo_ahorros'] /
    (df_base_saldos_cuentas['saldo_otros'] + 1e-6)
)

df_base_saldos_cuentas['prop_ahorros_total'] = (
    df_base_saldos_cuentas['saldo_ahorros'] /
    (df_base_saldos_cuentas['saldo_ahorros'] + df_base_saldos_cuentas['saldo_otros'] + 1e-6)
)

# -------------------------------------------------------------
# FILTRAR SOLO MES 12
# -------------------------------------------------------------
df_mes12 = df_base_saldos_cuentas[df_base_saldos_cuentas['mes'] == 12]

# -------------------------------------------------------------
# CREAR NUEVOS AGREGADOS POR ID
# -------------------------------------------------------------
df_agregados_ratio = df_mes12.groupby('ID', as_index=False).agg(
    ratio_ahorros_otros=('ratio_ahorros_otros', 'first'),
    prop_ahorros_total=('prop_ahorros_total', 'first')
)

# -------------------------------------------------------------
# UNIÓN CON LOS AGREGADOS ANTERIORES
# -------------------------------------------------------------
df_agregados_base_saldos_cuentas = pd.merge(
    df_agregados_base_saldos_cuentas,
    df_agregados_ratio,
    on='ID',
    how='left'
)

# -------------------------------------------------------------
# REVISIÓN FINAL
# -------------------------------------------------------------
print(f"Shape final: {df_agregados_base_saldos_cuentas.shape}")
df_agregados_base_saldos_cuentas.head()

Shape final: (784556, 49)

,ID,2_meses_max_saldo_ahorros,2_meses_min_saldo_ahorros,2_meses_sum_saldo_ahorros,2_meses_prom_saldo_ahorros,3_meses_max_saldo_ahorros,3_meses_min_saldo_ahorros,3_meses_sum_saldo_ahorros,3_meses_prom_saldo_ahorros,4_meses_max_saldo_ahorros,...,11_meses_sum_saldo_ahorros,11_meses_prom_saldo_ahorros,12_meses_max_saldo_ahorros,12_meses_min_saldo_ahorros,12_meses_sum_saldo_ahorros,12_meses_prom_saldo_ahorros,std_3m_ahorros,cv_3m_ahorros,ratio_ahorros_otros,prop_ahorros_total
0,00000f6dd2df6f081ce59cc4490f152e3fd5695de62bd9...,2.0478,1.9315,3.9793,1.98965,3.2484,1.9315,7.2277,2.409233,3.4815,...,16.2953,1.481391,3.4815,0.4939,16.8877,1.407308,0.535319,0.593831,1.931500e+06,0.999999
1,000043cc1abd7597c99f494cc523ff99a4e0e64e98b128...,3.5701,2.7086,6.2787,3.13935,3.5701,2.7086,9.1865,3.062167,3.5701,...,36.0873,3.280664,3.9980,2.3428,38.4301,3.202508,0.700319,0.244073,3.176217e+01,0.969477
2,000095b7b77ff622b2130f2d4bfa1e8d81f1fc4580a248...,3.9865,3.9865,7.9730,3.98650,3.9865,3.9865,11.9595,3.986500,3.9865,...,43.8515,3.986500,3.9865,3.9865,47.8380,3.986500,0.000000,0.000000,3.986500e+06,1.000000
3,00009bb00e84af44d1abc86b9fbd155842ffef6cad814d...,4.0610,4.0464,8.1074,4.05370,4.0791,4.0464,12.1865,4.062167,4.0946,...,46.4952,4.226836,4.3968,4.0464,50.7124,4.226033,0.094468,0.021848,4.046400e+06,1.000000
4,0000a9728fc57abef25c2fc0424c9c907a5559e7b8b559...,3.9150,2.8720,6.7870,3.39350,3.9150,2.8720,9.6760,3.225333,3.9150,...,30.7387,2.794427,3.9150,2.0286,33.7255,2.810458,0.021427,0.007207,3.915000e+06,1.000000

In [24]:
# Mes con mayor saldo
df_mes_max = (
    df_base_saldos_cuentas.groupby('ID')['saldo_ahorros']
    .idxmax().reset_index(name='mes_max_saldo')
)

# Mes con menor saldo
df_mes_min = (
    df_base_saldos_cuentas.groupby('ID')['saldo_ahorros']
    .idxmin().reset_index(name='mes_min_saldo')
)

# Número de meses consecutivos con caída de saldo
def meses_caida(x):
    return (x.diff() < 0).astype(int).rolling(3, min_periods=1).sum().iloc[-1]

df_caida = (
    df_base_saldos_cuentas.groupby('ID')['saldo_ahorros']
    .apply(meses_caida).reset_index(name='meses_caida_consecutiva')
)

# Unión con df_mes_max
df_agregados_base_saldos_cuentas = pd.merge(
    df_agregados_base_saldos_cuentas,
    df_mes_max,
    on='ID',
    how='left'
)

# Unión con df_mes_min
df_agregados_base_saldos_cuentas = pd.merge(
    df_agregados_base_saldos_cuentas,
    df_mes_min,
    on='ID',
    how='left'
)

# Unión con df_caida
df_agregados_base_saldos_cuentas = pd.merge(
    df_agregados_base_saldos_cuentas,
    df_caida,
    on='ID',
    how='left'
)

# Revisión final
print(f"Shape final: {df_agregados_base_saldos_cuentas.shape}")
df_agregados_base_saldos_cuentas.head()

Shape final: (784556, 52)

,ID,2_meses_max_saldo_ahorros,2_meses_min_saldo_ahorros,2_meses_sum_saldo_ahorros,2_meses_prom_saldo_ahorros,3_meses_max_saldo_ahorros,3_meses_min_saldo_ahorros,3_meses_sum_saldo_ahorros,3_meses_prom_saldo_ahorros,4_meses_max_saldo_ahorros,...,12_meses_min_saldo_ahorros,12_meses_sum_saldo_ahorros,12_meses_prom_saldo_ahorros,std_3m_ahorros,cv_3m_ahorros,ratio_ahorros_otros,prop_ahorros_total,mes_max_saldo,mes_min_saldo,meses_caida_consecutiva
0,00000f6dd2df6f081ce59cc4490f152e3fd5695de62bd9...,2.0478,1.9315,3.9793,1.98965,3.2484,1.9315,7.2277,2.409233,3.4815,...,0.4939,16.8877,1.407308,0.535319,0.593831,1.931500e+06,0.999999,6574850,2043247,1.0
1,000043cc1abd7597c99f494cc523ff99a4e0e64e98b128...,3.5701,2.7086,6.2787,3.13935,3.5701,2.7086,9.1865,3.062167,3.5701,...,2.3428,38.4301,3.202508,0.700319,0.244073,3.176217e+01,0.969477,5740473,5765000,2.0
2,000095b7b77ff622b2130f2d4bfa1e8d81f1fc4580a248...,3.9865,3.9865,7.9730,3.98650,3.9865,3.9865,11.9595,3.986500,3.9865,...,3.9865,47.8380,3.986500,0.000000,0.000000,3.986500e+06,1.000000,6066155,6066155,0.0
3,00009bb00e84af44d1abc86b9fbd155842ffef6cad814d...,4.0610,4.0464,8.1074,4.05370,4.0791,4.0464,12.1865,4.062167,4.0946,...,4.0464,50.7124,4.226033,0.094468,0.021848,4.046400e+06,1.000000,3447096,1829462,2.0
4,0000a9728fc57abef25c2fc0424c9c907a5559e7b8b559...,3.9150,2.8720,6.7870,3.39350,3.9150,2.8720,9.6760,3.225333,3.9150,...,2.0286,33.7255,2.810458,0.021427,0.007207,3.915000e+06,1.000000,8062034,699660,0.0

In [25]:
# 1️⃣ Renombrar columnas de df_base_saldos_cuentas (excepto la llave 'ID')
df_base_saldos_cuentas_prefixed = df_agregados_base_saldos_cuentas.rename(
    columns={col: f"DB_SAL_CUE_{col}" for col in df_agregados_base_saldos_cuentas.columns if col != 'ID'}
)

# 2️⃣ Hacer el LEFT JOIN con df_universo
df_universo = df_universo.merge(
    df_base_saldos_cuentas_prefixed,
    on='ID',
    how='left'
)

# 3️⃣ Verificación
print(df_universo.shape)
df_universo.head()

(535943, 84)

,ID,target,periodo,DB_CLI_edad,DB_CLI_ingreso,DB_CLI_anios_exp,DB_CLI_tipo_empleo,DB_CLI_buro_de_credito,DB_CLI_pago_nomina,DB_CLI_tc,...,DB_SAL_CUE_12_meses_min_saldo_ahorros,DB_SAL_CUE_12_meses_sum_saldo_ahorros,DB_SAL_CUE_12_meses_prom_saldo_ahorros,DB_SAL_CUE_std_3m_ahorros,DB_SAL_CUE_cv_3m_ahorros,DB_SAL_CUE_ratio_ahorros_otros,DB_SAL_CUE_prop_ahorros_total,DB_SAL_CUE_mes_max_saldo,DB_SAL_CUE_mes_min_saldo,DB_SAL_CUE_meses_caida_consecutiva
0,4d5a33701cb5b30b0b0a924d80de4ae78fbd0b54e2117f...,0,period_5,3.8498,4.6527,0.000,type_2,category_6,0.0,No,...,2.5149,39.5354,3.294617,0.894806,0.252333,3175400.0,1.0,7434408.0,3272878.0,1.0
1,bf7092e5f394d266143dfe90b3fc73eac51f0b0084d7a3...,0,period_5,4.5476,4.2447,4.274,type_3,category_4,0.0,No,...,3.2254,40.5731,3.381092,0.003002,0.000844,3225400.0,1.0,316982.0,2007939.0,0.0
2,270d8f8f607d19886c50edb7746c3670194134b56d31e2...,0,period_5,4.3600,4.2117,0.000,type_2,category_9,0.0,No,...,2.7090,42.1470,3.512250,0.005519,0.001410,2753000.0,1.0,4746546.0,546634.0,2.0
3,5e6b7bea5e4911329669f45728d3398ad54dfe11fbb16d...,0,period_5,4.3914,4.1584,0.000,type_7,category_2,0.0,No,...,3.7511,46.6400,3.886667,0.025317,0.006208,3751100.0,1.0,88699.0,3426600.0,2.0
4,98954adf775b9fce1c9e311a025ec3e0a1c6e90f991ef7...,0,period_5,4.3077,4.3285,0.000,type_2,category_6,0.0,No,...,2.6043,35.3925,2.949375,0.124250,0.045243,3408600.0,1.0,1906558.0,5074763.0,2.0

In [26]:
duplicados = df_universo.duplicated(subset='ID', keep=False).sum()
print(f"Número de registros con 'ID' duplicado: {duplicados}")

Número de registros con 'ID' duplicado: 0

In [27]:
# Exportar a CSV
nombre_archivo = 'df_universo.csv'
df_universo.to_csv(nombre_archivo, index=False)

print(f"DataFrame exportado exitosamente a: {nombre_archivo}")
print(f"Dimensiones del archivo final: {df_universo.shape}")

DataFrame exportado exitosamente a: df_universo.csv
Dimensiones del archivo final: (535943, 84)